# Copyright © ickk 2026.

[package]
name = "slimvec"
version = "0.2.3"
authors = ["ickk <crates@ickk.io>"]
license-file = "LICENSE.md"
license = "Zlib OR MIT OR Apache-2.0"
description = "Dynamic array with a smaller inline-size"
repository = "https://github.com/ickk/slimvec"
readme = "README.md"
edition = "2024"
categories = ["data-structures", "no-std"]
keywords = ["thin", "vec"]
include = [
  "README.md",
  "LICENSE.md",
  "src/",
  "docs/Overview.md",
  "docs/Architecture.md",
]

[dependencies]

[dev-dependencies]
impls = "1.0.3"

[features]
default = ["std"]
std = []
