# © ickk 2026.

[package]
name = "slimvec"
version = "0.1.2"
authors = ["ickk <crates@ickk.io>"]
license-file = "./LICENSE.md"
description = "Dynamic array with a smaller inline-size"
repository = "https://github.com/ickk/slimvec"
include = [
  "README.md",
  "LICENSE.md",
  "LICENSE-APACHE",
  "LICENSE-MIT",
  "LICENSE-ZLIB",
  "src/",
]
publish = false
edition = "2024"

[dependencies]

[dev-dependencies]
impls = "1.0.3"

[features]
default = ["std"]
std = []
