name: Rust
on: [push, pull_request, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v6
    - name: build
      run: cargo build --verbose

  build-no-default-features:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v6
    - name: build --no-default-features
      run: cargo build --no-default-features --verbose

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v6
    - name: test
      run: cargo test --verbose --no-fail-fast

  test-release:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v6
    - name: test --release
      run: cargo test --release --verbose --no-fail-fast

  miri:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v6
    - name: install miri
      run: rustup +nightly component add miri
    - name: miri test
      run: cargo +nightly miri test --verbose --no-fail-fast

  clippy:
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v6
    - name: clippy
      run: cargo clippy -- -Dwarnings

  rustfmt:
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v6
    - name: rustfmt
      run: cargo fmt --check

  package:
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v6
    - name: package --list
      run: cargo package --list -p slimvec
    - name: package
      run: cargo package -p slimvec
    - name: publish --dry-run
      run: cargo publish --dry-run -p slimvec
